services:
  backend_gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes:
      - /local_storage:/local_storage
      - /backend:/actuosus_ai
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////local_storage/default.db
      - BASE_FILE_STORAGE_PATH=/local_storage/models
      - DEBUG_MODE=True
      - HUGGINGFACE_TOKEN=
      # Add any additional environment variables needed by your app
  frontend:
    build:
      context: ./frontend  # Ensure this is the correct path to your frontend directory
      dockerfile: Dockerfile  # Your Dockerfile inside the /frontend folder
    volumes:
      - /frontend:/frontend
    ports:
      - "3000:3000"  # Exposing the frontend on port 3000 (adjust if needed)
    environment:
      - NODE_ENV=development  # Example environment variable for Node.js apps
      - PORT=3000
    depends_on:
      - backend_gpu  # Ensure backend is up before frontend starts