services:
  backend_gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes:
      - ./local_storage:/local_storage
      - ./backend:/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
      # Add any additional environment variables needed by your app
    command: [ "poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

  frontend:
    build:
      context: ./frontend  # Ensure this is the correct path to your frontend directory
      dockerfile: Dockerfile  # Your Dockerfile inside the /frontend folder
    volumes:
      - ./frontend/app:/frontend/app
    ports:
      - "3000:3000"  # Exposing the frontend on port 3000 (adjust if needed)
    environment:
      - NODE_ENV=development  # Example environment variable for Node.js apps
      - PORT=3000
    depends_on:
      - backend_gpu
    command: ["npm", "run", "dev"]