import type { Metadata } from "next";
import "./styles/globals.css";
import RootHeader from "@/app/components/RootHeader";
import {ToastContainer} from "react-toastify";

export const metadata: Metadata = {
  title: "ActuosusAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-2xl h-full">
      <body
        className={`antialiased h-full bg-background-800 text-primary-200`}
      >
      <RootHeader />
      <ToastContainer />
      <main>{children}</main>
      </body>
    </html>
  );
}
