import type { Metadata } from 'next';
import './globals.css';
import RootHeader from '@/app/components/RootHeader';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: 'ActuosusAI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-2xl h-full">
      <body className={`antialiased h-full bg-background-200 text-primary-950`}>
        {/*<RootHeader />*/}
        <ToastContainer />
        <main>{children}</main>
      </body>
    </html>
  );
}
